services:
  fastapi:
    container_name: fastapi-app
    image: fastapi-docker-example
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    labels:
      - "com.docker.desktop.port=8000"
    volumes:
      - ./app:/app
