version: "3.8"
services:
  greeter:
    build:
      context: ./cpp-server
      dockerfile: Dockerfile
    container_name: greeter
    ports:
      - "50051:50051"
    networks:
      - demo-net

  fastapi:
    build:
      context: ./py-client
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - greeter
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
